name: Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick python3-json-tool jq
        
    - name: Extract version from tag
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Check if this is a pre-release (contains alpha, beta, rc, or has dash/plus)
        if [[ $VERSION =~ (alpha|beta|rc|-|\+) ]]; then
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "This is a pre-release version: $VERSION"
        else
          echo "prerelease=false" >> $GITHUB_OUTPUT
          echo "This is a stable release version: $VERSION"
        fi
        
    - name: Update manifest version
      run: |
        # Update the version in manifest.json to match the tag
        jq --arg version "${{ steps.version.outputs.version }}" '.version = $version' manifest.json > manifest.tmp
        mv manifest.tmp manifest.json
        
        # Also update build manifest
        if [ -f "build/manifest.json" ]; then
          jq --arg version "${{ steps.version.outputs.version }}" '.version = $version' build/manifest.json > build/manifest.tmp
          mv build/manifest.tmp build/manifest.json
        fi
        
    - name: Build extension
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Verify build
      run: |
        if [ ! -f "click-the-cookie.zip" ]; then
          echo "Error: Extension zip file not created!"
          exit 1
        fi
        
        # Get file size for release notes
        SIZE=$(du -h click-the-cookie.zip | cut -f1)
        echo "Extension package size: $SIZE"
        echo "package_size=$SIZE" >> $GITHUB_ENV
        
    - name: Generate release notes
      id: release_notes
      run: |
        cat > release_notes.md << EOF
        # Click the Cookie ${{ steps.version.outputs.tag }}
        
        Firefox extension package for Click the Cookie.
        
        ## Installation
        
        ### Option 1: Temporary Install (Development)
        1. Download \`click-the-cookie.zip\` from this release
        2. Extract the zip file
        3. Open Firefox and navigate to \`about:debugging\`
        4. Click "This Firefox" in the left sidebar
        5. Click "Load Temporary Add-on..."
        6. Select the \`manifest.json\` file from the extracted folder
        
        ### Option 2: Package Install
        1. Download \`click-the-cookie.zip\` from this release
        2. Open Firefox and navigate to \`about:addons\`
        3. Click the gear icon and select "Install Add-on From File..."
        4. Select the \`click-the-cookie.zip\` file
        5. Note: May require setting \`xpinstall.signatures.required=false\` in \`about:config\`
        
        ## Package Details
        - **Size**: ${{ env.package_size }}
        - **Version**: ${{ steps.version.outputs.version }}
        - **Build Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        ## What's Included
        - Extension manifest and core files
        - Icons for Firefox toolbar and add-ons manager
        - All necessary files for Firefox installation
        
        ---
        
        *This extension currently has all features removed as per the project requirements.*
        EOF
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Click the Cookie ${{ steps.version.outputs.tag }}
        body_path: release_notes.md
        files: |
          click-the-cookie.zip
        prerelease: ${{ steps.version.outputs.prerelease }}
        draft: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ steps.version.outputs.tag }}
        path: |
          build/
          click-the-cookie.zip
          release_notes.md
        retention-days: 90
